# MySQL config reference: https://docs.getdbt.com/reference/warehouse-profiles/mysql-profile
#
# Warning: Do not store credentials in this file unless you've take the necessary steps to remove
# this file from your git commit.
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('MELTANO_ENVIRONMENT', 'dev') }}"  # The default profile name if no other profile is selected.
  outputs:
    # TODO: Optionally, revise or add to these profiles to reflect your own environments. Meltano adds dev, staging and prod by default.
    dev:
      type: mysql
      threads: 2
      account: "{{ env_var('DBT_MYSQL_ACCOUNT') }}"
      user: "{{ env_var('DBT_MYSQL_USER') }}"
      password: "{{ env_var('DBT_MYSQL_PASSWORD') }}"
      role: "{{ env_var('DBT_MYSQL_ROLE') }}"
      warehouse: "{{ env_var('DBT_MYSQL_WAREHOUSE') }}"
      database: "{{ env_var('DBT_MYSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MYSQL_SCHEMA') }}"
    staging:
      type: mysql
      threads: 4
      account: "{{ env_var('DBT_MYSQL_ACCOUNT') }}"
      user: "{{ env_var('DBT_MYSQL_USER') }}"
      password: "{{ env_var('DBT_MYSQL_PASSWORD') }}"
      role: "{{ env_var('DBT_MYSQL_ROLE') }}"
      warehouse: "{{ env_var('DBT_MYSQL_WAREHOUSE') }}"
      database: "{{ env_var('DBT_MYSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MYSQL_SCHEMA') }}"
    prod:
      type: mysql
      threads: 6
      account: "{{ env_var('DBT_MYSQL_ACCOUNT') }}"
      user: "{{ env_var('DBT_MYSQL_USER') }}"
      password: "{{ env_var('DBT_MYSQL_PASSWORD') }}"
      role: "{{ env_var('DBT_MYSQL_ROLE') }}"
      warehouse: "{{ env_var('DBT_MYSQL_WAREHOUSE') }}"
      database: "{{ env_var('DBT_MYSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MYSQL_SCHEMA') }}"
